turn_on:
  name: Turn on all outputs
  description: Turn AC and DC outputs ON

turn_off:
  name: Turn off all outputs
  description: Turn AC and DC outputs OFF

set_power_ac:
  name: Set AC output
  description: Set AC output state
  fields:
    state:
      name: State
      description: 0=off, 1=on
      default: true
      selector:
        boolean:
  target:
      entity:
        integration: cleanergy
        domain: switch
        device_class: switch

set_power_dc:
  name: Set DC output
  description: Set DC output state
  fields:
    state:
      name: State
      description: 0=off, 1=on
      default: true
      selector:
        boolean:
  target:
      entity:
        integration: cleanergy
        domain: switch
        device_class: switch
